#!/bin/bash

INPUTDIR="FULL_PATH_TO_YOUR_INPUT_DIR_HERE"
OUTPUTDIR="FULL_PATH_TO_YOUR_INPUT_DIR_HERE"
RULEDIR="FULL_PATH_TO_YOUR_RULES_DIR_HERE"

MEDTAGGER_DIR=$(cd `dirname $0` && pwd)
cd $MEDTAGGER_DIR

java -cp MedTagger.jar org.ohnlp.medtagger.fit.Main $INPUTDIR $OUTPUTDIR $RULEDIR