cd %~dp0

SET INPUTDIR=FULL_PATH_TO_YOUR_INPUT_DIR_HERE
SET OUTPUTDIR=FULL_PATH_TO_YOUR_INPUT_DIR_HERE
SET RULEDIR=FULL_PATH_TO_YOUR_RULES_DIR_HERE

java -cp MedTagger.jar org.ohnlp.medtagger.fit.Main %INPUTDIR% %OUTPUTDIR% %RULEDIR%